run_name: Photon-Allshower


data:
  path: /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/hhanif/tambo_simulations_for_training/combined_photons_balanced.h5 
  chunk_size: 10000  # load 50k samples at a time to avoid OOM on 350GB file
  samples_energy_trafo:
    - [Log, {alpha: 0.0}]
    - [StandardScaler, {shape: [1, 1]}]
  samples_coordinate_trafo:
    - [StandardScaler, {shape: [1, 1, 2]}]
  samples_time_trafo:
    - [Log, {alpha: 0.0}]
    - [StandardScaler, {shape: [1, 1]}]
  cond_trafo:
    - [Log, {alpha: 0.0}]
    - [StandardScaler, {shape: [1, 1]}]
  return_noise: True
  return_direction: True
  val_len: 30000
  max_num_points: 6016


model:
  num_layers: 24
  dim_inputs: [4, 6, 4]    # 3 → 4: x, y, e, t
  dim_embedding: 64
  num_head: 4
  num_blocks: 4
  dim_feedforward: 256
  num_points_cond: 512
  activation: GELU
  num_layer_cond: 8
  num_particles: 2
  flow_config:
    frequencies: 3

train:
  num_epochs: 200
  batch_size: 512
  learning_rate: 1.e-3
  optimizer: Ranger
  scheduler: Cosine
  weight_decay: 1.e-2
  grad_clip: 0.2
