run_name: Electron-PointCountFM
data:
  data_file: /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/hhanif/tambo_simulations_for_training/combined_electrons_balanced_for_pointcloud.h5
  transform_num_points:
    - [Dequantize]                    # smooths integers → floats
    - [Log, {alpha: 0.5}]
    - [StandardScaler, {shape: [1, 24]}]
  transform_inc:
    - [StandardScaler, {shape: [1, 1]}]
  batch_size: 1024
  batch_size_val: 4096
  num_val: 30000
  num_classes: 2
model:
  name: ConcatSquash
  dim_input: 24
  dim_condition: 6
  dim_time: 12
  hidden_dims:
  - 128
  - 256
  - 512
  - 256
  - 128
training:
  epochs: 500
  steps: 100
  optimizer:
    name: Adam
    lr: 0.001
  scheduler:
    name: OneCycleLR


# run_name: Electron-PointCountFM

# data:
#   data_file: /n/holylfs05/LABS/arguelles_delgado_lab/Everyone/hhanif/tambo_simulations_for_training/combined_electrons_balanced_for_pointcloud.h5
#   transform_num_points:
#     - [Log, {alpha: 0.5}]
#     - [StandardScaler, {shape: [1, 24]}]
#   transform_inc:
#     - [StandardScaler, {shape: [1, 1]}]
#   batch_size: 1024
#   batch_size_val: 4096
#   num_val: 30000
#   num_classes: 2

# model:
#   name: ConcatSquash
#   dim_input: 24
#   dim_condition: 6
#   dim_time: 12
#   hidden_dims:
#     - 256
#     - 512
#     - 1024
#     - 512
#     - 256
#   activation: SiLU
#   residual: True
#   layer_norm: True
#   flow:
#     frequencies: 6
#     acceleration: 0.3

# training:
#   epochs: 200
#   steps: 100  
#   optimizer:
#     name: AdamW
#     lr: 0.001
#     weight_decay: 0.0001
#   scheduler:
#     name: OneCycleLR